name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Executing remote ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 65.0.139.114
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd aws-cicd
            git pull
            npm install
            npm run build
            npm run start
