name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Executing remote ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.200.242.131
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd aws-cicd
            git pull
            npm install
            npm run build
            pm2 restart app || pm2 start npm --name "app" -- start
